development:
  adapter: mysql2
  database: accounted_api_development
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

test:
  adapter: mysql2
  database: accounted_api_test
  username: root
  password: root
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: postgres
  database: accounted_api_production